from datetime import date

from odoo.tests import tagged
from odoo.tests.common import TransactionCase


@tagged("post_install", "-at_install")
class TestBusinessTripTimesheetLog(TransactionCase):
    """Timesheets generated by a business trip are bookkeeping, not manual edits:
    they must not be logged in the attendance chatter."""

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.employee = cls.env["hr.employee"].create({"name": "Travelling Employee"})
        project = cls.env["project.project"].create({"name": "Trip Project", "allow_timesheets": True})
        cls.trip = cls.env["hr.business.trip"].create({
            "employee_id": cls.employee.id,
            "project_id": project.id,
            "date_from": date(2026, 1, 5),
            "date_to": date(2026, 1, 6),
        })

    def _timesheet_notes(self, attendances):
        return attendances.message_ids.filtered(lambda message: "Timesheet" in str(message.body))

    def test_approve_does_not_log_timesheets(self):
        self.trip.action_approve()
        self.assertEqual(len(self.trip.attendance_ids), 2)
        self.assertTrue(all(self.trip.attendance_ids.mapped("timesheet_ids")))
        self.assertFalse(self._timesheet_notes(self.trip.attendance_ids))

    def test_resync_does_not_log_timesheets(self):
        self.trip.action_approve()
        kept = self.trip.attendance_ids.filtered(lambda att: att.check_in.date() == date(2026, 1, 5))
        self.trip.write({"date_to": date(2026, 1, 5), "note": "Shortened trip"})
        self.assertEqual(self.trip.attendance_ids, kept)
        self.assertFalse(self._timesheet_notes(kept))
